### ISSUE TITLE
Add releases, tags and binaries

### ISSUE THREAD

**Issue by markus-wa** [vburenin/ifacemaker#27]
I think it would be great to have another way to get binaries than using go get.

That way it would be easier to get everyone in a project to use the same version of `ifacemaker` and it would ensure reproducible builds in CI (For example to verify the checked in interfaces are up-to-date).

I came across this while looking into it a bit:
https://github.com/goreleaser/goreleaser

Either way a great start would be having tags/releases and pre-built binaries for say Windows, Linux and OSX.

I'd be more than happy to add Travis and GoReleaser to the repo if you'd be interested in that. You would then just need to authorize GoReleaser and Travis (and some minimal configuration).

**Comment by vburenin** [comment]
I am happy to do code reviews and merge the contributed code. 

ps. If I do not respond longer than four days, ping me again.

**Comment by markus-wa** [comment]
hey!

I saw you actually tagged v1.0.0 a while ago (https://github.com/vburenin/ifacemaker/releases/tag/v1.0.0)

But it seems like the build failed due to a missing GITHUB_TOKEN: https://travis-ci.com/vburenin/ifacemaker/jobs/170104260#L528

I think you have to go to https://travis-ci.com/vburenin/ifacemaker/settings
and add a environment variable `GITHUB_TOKEN` which is a personal access token https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line

After that simply re-run the failed job and hopefully the binaries should be added to the release page here: https://github.com/vburenin/ifacemaker/releases

**Comment by vburenin** [comment]
gosh, I missed this comment from you somehow.

**Comment by vburenin** [comment]
fixed

**Comment by markus-wa** [comment]
Awesome, thank you!

> gosh, I missed this comment from you somehow.

no worries :slightly_smiling_face:
