### ISSUE TITLE
go get fails

### ISSUE THREAD

**Issue by lox** [vburenin/ifacemaker#37]
I'm seeing this:

```
$ go get github.com/vburenin/ifacemaker
# github.com/vburenin/ifacemaker
go/src/github.com/vburenin/ifacemaker/ifacemaker.go:79:6: undefined: flags.WroteHelp
```

**Comment by vburenin** [comment]
It is likely incompatible global dependency on your side. I have managed to run ```go get``` on a complete clean Ubuntu 18.04 environment. as well as I tested it with go modules, it gets built just fine.

**Comment by lox** [comment]
Thanks, I can confirm it works in a clean env too. That's odd, I was under the impressions that modules should fix that issue!
