### ISSUE TITLE
Imported packages that end with the name of the current package are replaced incorrectly

### ISSUE THREAD

**Issue by UnacceptableUse** [vburenin/ifacemaker#42]
e.g 
```
package xyz

import "example.com/abcdxyz"

type Demo struct {
}

func (demo *Demo) TestFunction(input abcdxyz.ImportedType){

}
```

would create an interface of

```
package x

type Demo interface{
   TestFunction(input abcdImportedType)
}
```

The offending line of code is here:
https://github.com/vburenin/ifacemaker/blob/master/maker/maker.go#L100

**Comment by vburenin** [comment]
Thanks a lot! Could you fix it please and submit PR? I will not be able to get access to my dev environment for months to come :(
