### ISSUE TITLE
Add example on how to use ifacemaker with go:generate

### ISSUE THREAD

**Issue by migueleliasweb** [vburenin/ifacemaker#45]
Hi,

It would be awesome it there were examples on how to use `ifacemaker` with `go:generate` directives.

Cheers!

**Comment by muzykantov** [comment]
> Hi,
> 
> It would be awesome it there were examples on how to use `ifacemaker` with `go:generate` directives.
> 
> Cheers!

//go:generate ifacemaker -f network/binance_client.go -p binancecom -s BinanceClient -i Client -o client.go -y "Client interface describes wrapped binance connection client."
