### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by migueleliasweb** [vburenin/ifacemaker#46]
The latest available release doesn't seem to be up-to-date with the latest changes in the codebase.

Should a new one be created?

**Comment by chenrui333** [comment]
cc @vburenin

**Comment by chenrui333** [comment]
bump this

**Comment by vancluever** [comment]
@kazhuravlev I see you're the last committer on this, would this be possible? We have tooling that can't install off of branch/sha so need a release tag to work off of.

**Comment by kazhuravlev** [comment]
@vancluever I am not a maintainer/owner. I cannot do anything (only create a fork and support it in my repo?). This tool is looks like abandoned. 

Anyway, in case that you want to use the latest changes from `master` - you can do it without tags like

```
go install github.com/vburenin/ifacemaker@187c3829a589ed2a580731a000f7a4f61cc01e80
```

where `187c3829a589ed2a580731a000f7a4f61cc01e80` is a hash of commit in this repo

**Comment by vburenin** [comment]
it is not really abandoned, it simply works without changes where it supposed to. however, I haven't tested it with generics.

**Comment by vancluever** [comment]
@vburenin indeed it does work and we are using it :) Thanks for cutting the release @vburenin!

**Comment by vburenin** [comment]
You are welcome. I haven't build binaries though. Travis CI is asking for $ due to too many users.
On my end it is always built from sources, releases are kinda not necessary.

**Comment by vancluever** [comment]
@vburenin looks like the release was created against an old commit and does not include recent changes like #52 which we need. Can you tag another release quick?

**Comment by vburenin** [comment]
hm...

**Comment by vburenin** [comment]
republished it as v1.2.1, hopefully it works.

**Comment by vancluever** [comment]
@vburenin looking good now, thanks for your help!
