### ISSUE TITLE
Extra newline at the end of the file

### ISSUE THREAD

**Issue by nkovacs** [vburenin/ifacemaker#5]
ifacemaker appends an extra newline at the end of the file: https://github.com/vburenin/ifacemaker/blob/master/ifacemaker.go#L39

gofmt doesn't like this newline, and will remove it.

Why is this newline added to the result? FormatCode should format the code properly.

**Comment by vburenin** [comment]
I do not remember exactly, it was a two hours project that I desperately needed for testing purposes. It could be for esthetic purposes or just a leftover.
anyway, thanks for contribution!
