### ISSUE TITLE
Why it's so slow?

### ISSUE THREAD

**Issue by wirekang** [vburenin/ifacemaker#50]
Is there any solution to speed up ifacemaker? (or alternative package)

**Comment by vburenin** [comment]
Can you be more specific? What is slow exactly? can you provide any example? It was always instantaneous.

**Comment by wirekang** [comment]
I make batch file that calls ```ifacemaker``` 10 times, target files are about 500 lines in total. In my i5-9400 cpu, whole operation takes 20 seconds.

Entire project(not mine, I can't open it to public) is about 2,000 lines.

![image](https://user-images.githubusercontent.com/43294688/160074016-6fc326b3-941c-4e2d-82ee-e05e0d20b36f.png)

Is 20sec is normal?

I think ifacemaker build whole project every call. If is, that would be bottleneck. Is there any solution to extract multiple interfaces in a call?

**Comment by wirekang** [comment]
I found the bottleneck!!! ```FormatCode``` takes up 99% of the running times in my environment. I don't know why. Please check #51

**Comment by vburenin** [comment]
@wirekang 20 seconds is definitely too slow for some reason it has to be on milliseconds level. Looking at your output it looks like you are running it all on windows, it might be a cause. Do you have external dependencies? Do you run AV?

**Comment by vburenin** [comment]
@wirekang I updated formatter to the latest one, try again.

**Comment by wirekang** [comment]
Same as before. I don't use anti-virus except Windows default. Target code have many external dependencies.

**Comment by vburenin** [comment]
@wirekang Do you use goimports tool?

**Comment by wirekang** [comment]
> @wirekang Do you use goimports tool?

Yes, and I'm using goimports instead of imports because of this issue.
![image](https://user-images.githubusercontent.com/43294688/160132818-f03637da-6e63-42be-8197-1a9cc3e60e6e.png)

**Comment by vburenin** [comment]
interesting, ifacemaker depends on goimports and technically uses it to format the code.

**Comment by wirekang** [comment]
> interesting, ifacemaker depends on goimports and technically uses it to format the code.

I just knew that ```goimports``` using ```imports``` internally...

**Comment by vburenin** [comment]
goimports does a lot more than that. It removes unused imports, adds missing imports, etc. This is the whole point of using it. You can't just disable it via options.

**Comment by wirekang** [comment]
I understand. I just closed #51

**Comment by wirekang** [comment]
> @wirekang I updated formatter to the latest one, try again.

Sorry for confusing you. ```go install ...@latest``` command treat latest tagged version as latest version. After I install latest commit version via ```go install github.com/vburenin/ifacemaker@640e39d```, The problem has been solved. Release new version please. I sincerely apologize for not thinking about it.
